name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
      - run: terraform fmt -check -recursive
